### ISSUE TITLE
Wifi hotspot not working. face lock not working . screen casting not working perfectly

### ISSUE THREAD

**Issue by sebu9495** [PixelExperience-Devices/device_motorola_payton#1]
Wifi hotspot not working. face lock not working . screen casting not working perfectly
![IMG_20200124_115248](https://user-images.githubusercontent.com/41418122/73059985-ec73b080-3ebc-11ea-86ef-abaa044f4412.jpg)
![Screenshot_20200124-115406](https://user-images.githubusercontent.com/41418122/73059988-ec73b080-3ebc-11ea-946f-3a9298b20c87.png)
![Screenshot_20200124-151958](https://user-images.githubusercontent.com/41418122/73060040-ff868080-3ebc-11ea-994b-f3291e5795d1.png)

**Comment by trpsl** [comment]
fixed hotspot and screen cast in latest build: https://download.pixelexperience.org/changelog/payton/PixelExperience_payton-10.0-20200125-2121-OFFICIAL.zip/

face unlock is dropped by google in android Q, see https://support.google.com/pixelphone/thread/13539143?hl=en
